services:
  - type: web
    name: orchestrator-isa-os
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: ADMIN_USER
        value: isa
      - key: ADMIN_PASS
        value: orchestrator2024
